
def start_question():
    start_questions = ["Situated in Europe?", "Situated in Asia?", "Situated in Africa?",
     "Situated in South?", "Situated in North?", "Situated in Oceany?"]
    return start_questions


def countries_question():
    countries_questions = [["Speaks Dutch", "Flag with Blue cross?", "Speaks English",
      "Speaks Italien", "Speaks French ?", "Speaks German ?",
      "Situated in the Nordic region?", "Touches sea mediterean ?", "Part of Yougoslavia ?",
      "Flag has 3 or more colors ?", "Flag with a cross?", "Flag contains red?",
      "Pop over 30m ?", "Pop over 10m ?", "Population over 5m", "In Europe Union ?",
      "euro in your country?"],
     ["pop over 100m?", "pop over 30m?", "pop over 10m?", "pop over 5m?",
      "middle east?", "arabic?", "Hindu?", "Folk religion?", "christian?", "Buddhist?", "muslim?",
      "island?", "touches indian ocean?", "pacific ocean?", "flag contains red?",
      "flag contains blue?", "flag contains green?", "flag contains yellow?",
      "star on the flag?", "moon on the flag?", "circled object or sun on the flag?"],
     ["pop over 30m?", "pop over 10m?", "pop over 5m?", "Island ?",
      "french ?", "english?", "arabic?", "portuguese", "flag contains 3 or more color",
      "flag contains red?", "flag contains blue?", "flag contains green?",
      "flag contains yellow?", "Dominant Religion Muslim?", "Dominant Religion Christian?",
      "touches atlantic ocean?(including mediterranen sea)",
      "countries touching indian ocean?(including the red sea,arabian sea)",
      "star on the flag?", "moon on the flag?"],
     ["Speaks Spanish ?", "Amazon forest in your country ?", "Population over 30m?",
      "Population over 10m?", "Population over 5m?", "Touch atlantic ocean ?",
      "Touch pacific ocean?", "Flag contains red?", "Flag contains blue?",
      "Flag contains green?", "star on your flag?", "cicrle or sun on your flag?"],
     ["pop over 30m", "pop over 10m", "pop over 5m", "spanish?", "english?",
      "flag contains red?", "flag contains blue?", "flag contains yellow?",
      "flag contains green?", "flag contains star?", "flag contains black?",
      "country touches atlantic ocean?", "country touching pacific ocean?"],
     ["pop over 10m?", "pop over 1 million?", "flag contains green?",
      "flag contains blue?", "flag contains stars?", "flag contains red?",
      "flag contains yellow?"]]
    return countries_questions


def countries_list():
    countries_lists = [["Albania", "Andorra", "Austria", "Belarus", "Belgium", "Bosnia and Herzegovina", "Bulgaria", "Croatia",
      "Czech Republic", "Cyprus", "Denmark", "Estonia", "Finland", "France", "Georgia", "Germany", "Greece",
      "Hungary", "Iceland", "Ireland", "Italy", "Latvia", "Liechtenstein", "Lithuania", "Luxembourg",
      "Malta",
      "Moldova", "Monaco", "Montenegro", "Netherlands", "North Macedonia", "Norway", "Poland", "Portugal",
      "Romania", "Russia", "San Marino", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden", "Switzerland",
      "Turkey", "Ukraine", "United Kingdom"],
    ["Afghanistan", "Armenia", "Azerbaijan", "Bahrain",
    "Bangladesh", "Bhutan", "Brunei", "Cambodia", "China",
           "India", "Indonesia", "Iran", "Iraq", "Israel",
           "Japan", "Jordan", "Kazakhstan", "Kuwait", "Kyrgyzstan",
           "Laos", "Lebanon", "Malaysia", "Maldives",
           "Mongolia", "Myanmar", "Nepal", "North Korea", "Oman",
           "Pakistan", "Philippines", "Qatar", "Saudi Arabia",
           "Singapore", "South Korea", "Sri Lanka", "Palestine", "Syria",
           "Tajikistan", "Thailand", "Timor-Leste",
           "Turkmenistan", "United Arab Emirates", "Uzbekistan",
           "Vietnam", "Yemen"],
     ["Algeria", "Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cabo Verde", "Cameroon",
      "Central African Republic", "Chad", "Comoros", "Congo", "Côte d'Ivoire", "Djibouti", "DR Congo",
      "Egypt",
      "Equatorial Guinea", "Eritrea", "Eswatini", "Ethiopia", "Gabon", "Gambia", "Ghana", "Guinea",
      "Guinea-Bissau",
      "Kenya", "Lesotho", "Liberia", "Libya", "Madagascar", "Malawi", "Mali", "Mauritania", "Mauritius",
      "Morocco",
      "Mozambique", "Namibia", "Niger", "Nigeria", "Rwanda", "Sao Tome and Principe", "Senegal",
      "Seychelles",
      "Sierra Leone", "Somalia", "South Africa", "South Sudan", "Sudan", "Tanzania", "Togo", "Tunisia",
      "Uganda",
      "Zambia", "Zimbabwe"],
     ["Argentina", "Bolivia", "Brazil", "Chile", "Colombia", "Ecuador", "Guyana", "Paraguay",
      "Peru", "Suriname", "Uruguay", "Venezuela"],
     ["Antigua and Barbuda", "Bahamas", "Barbados", "Belize", "Canada", "Costa Rica", "Cuba",
      "Dominica", "Dominican Republic", "El Salvador", "Grenada", "Guatemala", "Haiti",
      "Honduras", "Jamaica", "Mexico", "Nicaragua", "Panama", "Saint Kitts and Nevis",
      "Saint Lucia", "St. Vincent and Grenadines", "Trinidad and Tobago",
      "United States of America"],
     ["Australia", "Fiji", "Kiribati", "Marshall Islands", "Micronesia", "Nauru", "New Zealand", "Palau",
      "Papua New Guinea", "Samoa", "Solomon Islands", "Tonga", "Tuvalu", "Vanuatu"]]
    return countries_lists